name 'mcxess-freeswitch'
maintainer 'Myroslav Rys'
maintainer_email 'stonevil@gmail.com'
license 'All rights reserved'
description 'Installs/Configures FreeSwitch for MCXess'
long_description 'Installs/Configures FreeSwitch for MCXess'
version '0.1.0'

depends 'yum'
depends 'freeswitch'
depends 'resolver'
